Utils and stuffs added. My first testcase #4 for code review
Fulcrum81/AugSep2022-Autotest pull request #4
Opened 2022-09-17 08:56 UTC by andrej-khatkevich

Tread.sleep() sucks but no waits are working :(

2022-09-18 09:00 UTC, andrej-khatkevich commented
Found a way to replace Thread.sleep()

2022-10-01 21:24 UTC, Fulcrum81 requested changes

2022-10-01 21:24 UTC, Fulcrum81 commented on RubberDucksTest/src/test/java/mavenizer/staticPO/CataloguePage.java
> +    public static void addDucksToCart(WebDriver driver, Ducks duckType, String ducksQuantity) {
since it's a number better use int, rather than string

2022-10-02 07:06 UTC, andrej-khatkevich commented on RubberDucksTest/src/test/java/BinTest.java
> -    public void cartAmountTestNoMatterOfCurrency() {
Exactly. This was an example of where to place tests for our team

2022-10-02 07:08 UTC, andrej-khatkevich commented on RubberDucksTest/src/test/java/BinTest.java
> +        categoriesInBinCount++;
You are absolutely right. My fail. Fixed

2022-10-02 07:12 UTC, andrej-khatkevich commented on RubberDucksTest/src/test/java/BinTest.java
> +    @Description("Method adds categories(3) of ducks(3) to bin. Then removes it step by step " +
Fixed

2022-10-02 07:24 UTC, andrej-khatkevich commented on RubberDucksTest/src/test/java/BinTest.java
> +            new WebDriverWait(driver, Duration.ofSeconds(2))
Moved to Waits class as static method

2022-10-02 07:43 UTC, andrej-khatkevich commented on RubberDucksTest/src/test/java/BinTest.java
> +        Assert.assertEquals(driver.findElement(LocatorHelper.getLocator("CartPage.inputField")).getAttribute("value"),
Fixed

2022-10-02 07:51 UTC, andrej-khatkevich commented on RubberDucksTest/src/test/java/BinTest.java
> +        Assert.assertEquals(driver.findElement(LocatorHelper.getLocator("CartPage.inputField")).getAttribute("value"),
Yea, thank you. Moved this code to separate method in CartPage

2022-10-02 07:54 UTC, andrej-khatkevich commented on RubberDucksTest/src/test/java/BinTest.java
> +        Assert.assertEquals(driver.findElement(LocatorHelper.getLocator("CartPage.inputField")).getAttribute("value"),"1");
Fixed

2022-10-02 07:59 UTC, andrej-khatkevich commented on RubberDucksTest/src/test/java/mavenizer/helpers/OrderSummaryRecord.java
> +public class OrderSummaryRecord {
Moved to dto package

2022-10-02 07:59 UTC, andrej-khatkevich commented on RubberDucksTest/src/test/java/mavenizer/helpers/OrderSummaryTableMapper.java
> +            builder.append(record.getQuantity()).append(" : ").append(record.getProduct()).append(" : ").append(record.getSku())
Ok

2022-10-02 08:00 UTC, andrej-khatkevich commented on RubberDucksTest/src/test/java/mavenizer/helpers/StringHelper.java
> +    public static String calculateTotals(String unitPrice, int quantity) {
Thank you

2022-10-02 08:24 UTC, andrej-khatkevich commented on RubberDucksTest/src/test/java/mavenizer/staticPO/CartPage.java
> +    public static List<WebElement> getCategoriesLiList(WebDriver driver) {
I meant tag <li>. Renamed to getCategoriesLinksList.
I moved this method to CartPage cause I need refresh all links in cycle.
Clicking 'Remove' button completely changes DOM and old links stays invalid :(
Thare are another methods with same "get element" aproach like getRemoveButtonByIndex for catching link dynamically, or getOrderSummaryTable.. What is the right place for these methods? Another package?

2022-10-02 08:25 UTC, andrej-khatkevich commented on RubberDucksTest/src/test/java/mavenizer/staticPO/CataloguePage.java
> +    public static void addDucksToCart(WebDriver driver, Ducks duckType, String ducksQuantity) {
Fixed

2022-10-02 10:06 UTC, Fulcrum81 approved these changes

2022-10-02 15:23 UTC, QAEvgenyZarytsky commented
Checked! Everything works correctly!

2022-10-02 15:39 UTC, QAEvgenyZarytsky approved these changes
It's good job!

2022-10-02 15:40 UTC, merged

2022-10-02 16:59 UTC, andrej-khatkevich commented
Thanks for All